title: AutoAI-FM Workshop
description: >
  AutoAI meets Foundation Models - An IJCAI-ECAI 2026 Workshop
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://autoaifm.github.io" # the base hostname & protocol for your site

# minimal mistakes setup
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

atom_feed:
  hide: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

include: ['_2016_pages', '_2017_pages']

# Default layouts and settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: false
      sidebar: null
      header:
        overlay_image: null

# Build settings
markdown: kramdown
permalink: pretty